language: r
sudo: required
warnings_are_errors: true
cache: packages
before_install:
  -  openssl aes-256-cbc -K $encrypted_dc184331e475_key -iv $encrypted_dc184331e475_iv -in tests/testthat/token_file.rds.enc -out tests/testthat/token_file.rds -d
after_success:
- Rscript -e 'covr::codecov()'
notifications:
  email:
    on_success: change
    on_failure: always

